### PR TITLE
clean readme

### PR DESCRIPTION
**Pull request by kang-ghtester**

### CODE REVIEW

**Comment by kang-ghtester** [comment]
As I had a previous merge, this pipeline ran automatically without approval.

This is de debug info:
```
repository_owner: "newrelic-forks"
triggering_actor: "kang-ghtester"
actor:            "kang-ghtester"
```
And the remove label step run but had no label to remove.

Pipeline failed as intended.

**Comment by kang-makes** [comment]
I labeled the PR as `ci/allow-external`. The pipeline ran again:
```
repository_owner: "newrelic-forks"
triggering_actor: "kang-makes"
actor:            "kang-makes"
```
The step to remove the label was not run and the pipeline finished green.

**Comment by kang-ghtester** [comment]
Here I was able to modify de pipeline and I managed to do it. Security hole:
```
repository_owner: "newrelic-forks"
triggering_actor: "kang-ghtester"
actor:            "kang-ghtester"
```

I am changing the configuration of this repository to have to approve everything that is from outside

**Comment by kang-makes** [comment]
I am changing the configuration of this repository to have to approve everything that is from outside.

CLosing PR. @kang-ghtester should create a new PR from `main`.

**Pull request closed without merging**
